server:
  port: 8090
spring:
  cloud:
    nacos:

      discovery:
        cluster-name: ShangHai #配置集群
        server-addr: localhost:8848

  application:
    name: mallShowImageService
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 350MB

logging:
  level:
    com.ntx: debug
ribbon:
  eager-load:
    enabled: true


#eureka:
#  client:
#    service-url:
#      defaultZone: http:127.0.0.1:10086/eureka